apiVersion: apps/v1
kind: Deployment
metadata:
  name: register-ops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: register-ops
  template:
    metadata:
      labels:
        app: register-ops
    spec:
      serviceAccountName: register-ops
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: register-ops
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
{{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.port }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.port }}
          securityContext:
            readOnlyRootFilesystem: true
