apiVersion: v1
kind: Service
metadata:
  name: register-ops
  labels:
    app: register-ops
spec:
  selector:
    app: register-ops
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
