repositories:
  - name: jetstack
    url: https://charts.jetstack.io
  - name: aws
    url: https://aws.github.io/eks-charts
  - name: external-secrets
    url: https://charts.external-secrets.io
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

releases:
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: v1.14.4
    values:
      - installCRDs: true
  - name: aws-load-balancer-controller
    namespace: kube-system
    chart: aws/aws-load-balancer-controller
  - name: external-secrets
    namespace: external-secrets
    chart: external-secrets/external-secrets
  - name: kube-prometheus-stack
    namespace: monitoring
    chart: prometheus-community/kube-prometheus-stack
