name: Terraform

on:
  pull_request:
    paths:
      - 'infra/terraform/**'
  push:
    branches: [main]
    paths:
      - 'infra/terraform/**'

permissions:
  contents: read
  id-token: write

jobs:
  fmt-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Terraform fmt
        run: terraform -chdir=infra/terraform fmt -check
      - name: Terraform validate
        run: terraform -chdir=infra/terraform validate

  plan:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1
      - name: Terraform plan
        run: terraform -chdir=infra/terraform/envs/staging plan

  apply:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: fmt-validate
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1
      - name: Terraform apply
        run: terraform -chdir=infra/terraform/envs/staging apply -auto-approve
