name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g., v1.2.3)'
        required: true
      changelog:
        description: 'Release notes'
        required: false

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
      - name: Tag release
        run: |
          git tag ${{ inputs.version }}
          git push origin ${{ inputs.version }}
      - name: Build
        run: |
          cmake -S . -B build -DAPP_VERSION=${{ inputs.version }}
          cmake --build build --target register_mvp --config Release
      - name: Package artifact
        run: |
          tar -czf register_mvp-${{ inputs.version }}.tar.gz -C build register_mvp
      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ inputs.version }}
          name: ${{ inputs.version }}
          body: ${{ inputs.changelog }}
          files: register_mvp-${{ inputs.version }}.tar.gz
